<?php

/**
 * @file
 * Contains hs_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hs_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_api module.
    case 'help.page.hs_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is custom rest api module') . '</p>';
      return $output;

    default:
  }
}
